=== ATomilov/elements_table/elements_table.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT atomic_namber (#PCDATA)>
<!ELEMENT atomic_mass (#PCDATA)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT electrons_on_layer (#PCDATA)>
<!ELEMENT symbol (#PCDATA)>
<!ELEMENT kind (#PCDATA)>
<!ELEMENT group (#PCDATA)>
<!ELEMENT period (#PCDATA)>
<!ELEMENT position (group, period)>
<!ATTLIST element id CDATA #REQUIRED>
<!ELEMENT element (atomic_namber, atomic_mass, name, electrons_on_layer, symbol, kind, position)>
<!ELEMENT elements (element)+>
<!ELEMENT elements_table (elements)>

=== ATomilov/elements_table/elements_table_static.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="output_static.xsl"?>
<!DOCTYPE elements_table SYSTEM "elements_table.dtd">
<elements_table>
  <elements>
    <element id="e_1">
      <atomic_number>1</atomic_number>
      <atomic_mass>1.007</atomic_mass>
      <name>Водород</name>
      <electrons_on_layer>1</electrons_on_layer>
      <symbol>H</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>1</group>
        <period>1</period>
      </position>
    </element>
    <element id="e_2">
      <atomic_number>2</atomic_number>
      <atomic_mass>4.002</atomic_mass>
      <name>Гелий</name>
      <electrons_on_layer>2</electrons_on_layer>
      <symbol>He</symbol>
      <kind>Инертные газы</kind>
      <position>
        <group>18</group>
        <period>1</period>
      </position>
    </element>
    <element id="e_3">
      <atomic_number>3</atomic_number>
      <atomic_mass>6.941</atomic_mass>
      <name>Литий</name>
      <electrons_on_layer>2-1</electrons_on_layer>
      <symbol>Li</symbol>
      <kind>Щелочные металлы</kind>
      <position>
        <group>1</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_4">
      <atomic_number>4</atomic_number>
      <atomic_mass>9.012</atomic_mass>
      <name>Берилий</name>
      <electrons_on_layer>2-2</electrons_on_layer>
      <symbol>Be</symbol>
      <kind>Щелочноземельные металлы</kind>
      <position>
        <group>2</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_5">
      <atomic_number>5</atomic_number>
      <atomic_mass>10.811</atomic_mass>
      <name>Бор</name>
      <electrons_on_layer>2-3</electrons_on_layer>
      <symbol>B</symbol>
      <kind>Полуметаллы</kind>
      <position>
        <group>13</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_6">
      <atomic_number>6</atomic_number>
      <atomic_mass>12.011</atomic_mass>
      <name>Углерод</name>
      <electrons_on_layer>2-4</electrons_on_layer>
      <symbol>C</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>14</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_7">
      <atomic_number>7</atomic_number>
      <atomic_mass>14.007</atomic_mass>
      <name>Азот</name>
      <electrons_on_layer>2-5</electrons_on_layer>
      <symbol>N</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>15</group>
        <period>1</period>
      </position>
    </element>
    <element id="e_8">
      <atomic_number>8</atomic_number>
      <atomic_mass>15.999</atomic_mass>
      <name>Кислород</name>
      <electrons_on_layer>2-6</electrons_on_layer>
      <symbol>O</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>16</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_9">
      <atomic_number>9</atomic_number>
      <atomic_mass>18.998</atomic_mass>
      <name>Фтор</name>
      <electrons_on_layer>2-7</electrons_on_layer>
      <symbol>F</symbol>
      <kind>Галогены</kind>
      <position>
        <group>17</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_10">
      <atomic_number>10</atomic_number>
      <atomic_mass>20.18</atomic_mass>
      <name>Неон</name>
      <electrons_on_layer>2-8</electrons_on_layer>
      <symbol>Ne</symbol>
      <kind>Инертные газы</kind>
      <position>
        <group>18</group>
        <period>2</period>
      </position>
    </element>
    <element id="e_11">
      <atomic_number>11</atomic_number>
      <atomic_mass>22.99</atomic_mass>
      <name>Натрий</name>
      <electrons_on_layer>2-8-1</electrons_on_layer>
      <symbol>Na</symbol>
      <kind>Щелочные металлы</kind>
      <position>
        <group>1</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_12">
      <atomic_number>12</atomic_number>
      <atomic_mass>24.305</atomic_mass>
      <name>Магний</name>
      <electrons_on_layer>2-8-2</electrons_on_layer>
      <symbol>Mg</symbol>
      <kind>Щелочноземельные металлы</kind>
      <position>
        <group>2</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_13">
      <atomic_number>13</atomic_number>
      <atomic_mass>26.982</atomic_mass>
      <name>Алюминий</name>
      <electrons_on_layer>2-8-3</electrons_on_layer>
      <symbol>Al</symbol>
      <kind>Постпереходные металлы</kind>
      <position>
        <group>13</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_14">
      <atomic_number>14</atomic_number>
      <atomic_mass>28.086</atomic_mass>
      <name>Кремний</name>
      <electrons_on_layer>2-8-4</electrons_on_layer>
      <symbol>Si</symbol>
      <kind>Полуметаллы</kind>
      <position>
        <group>14</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_15">
      <atomic_number>15</atomic_number>
      <atomic_mass>30.974</atomic_mass>
      <name>Фосфор</name>
      <electrons_on_layer>2-8-5</electrons_on_layer>
      <symbol>P</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>15</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_16">
      <atomic_number>16</atomic_number>
      <atomic_mass>32.065</atomic_mass>
      <name>Сера</name>
      <electrons_on_layer>2-8-6</electrons_on_layer>
      <symbol>S</symbol>
      <kind>Неметаллы</kind>
      <position>
        <group>16</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_17">
      <atomic_number>17</atomic_number>
      <atomic_mass>35.453</atomic_mass>
      <name>Хлор</name>
      <electrons_on_layer>2-8-7</electrons_on_layer>
      <symbol>Cl</symbol>
      <kind>Галогены</kind>
      <position>
        <group>17</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_18">
      <atomic_number>18</atomic_number>
      <atomic_mass>39.948</atomic_mass>
      <name>Аргон</name>
      <electrons_on_layer>2-8-8</electrons_on_layer>
      <symbol>Ar</symbol>
      <kind>Инертные газы</kind>
      <position>
        <group>18</group>
        <period>3</period>
      </position>
    </element>
    <element id="e_19">
      <atomic_number>19</atomic_number>
      <atomic_mass>39.098</atomic_mass>
      <name>Калий</name>
      <electrons_on_layer>2-8-8-1</electrons_on_layer>
      <symbol>K</symbol>
      <kind>Щелочные металлы</kind>
      <position>
        <group>1</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_20">
      <atomic_number>20</atomic_number>
      <atomic_mass>40.078</atomic_mass>
      <name>Кальций</name>
      <electrons_on_layer>2-8-8-2</electrons_on_layer>
      <symbol>Ca</symbol>
      <kind>Щелочноземельные металлы</kind>
      <position>
        <group>2</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_21">
      <atomic_number>21</atomic_number>
      <atomic_mass>44.956</atomic_mass>
      <name>Скандий</name>
      <electrons_on_layer>2-8-9-2</electrons_on_layer>
      <symbol>Sc</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>3</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_22">
      <atomic_number>22</atomic_number>
      <atomic_mass>47.867</atomic_mass>
      <name>Титан</name>
      <electrons_on_layer>2-8-10-2</electrons_on_layer>
      <symbol>Ti</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>4</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_23">
      <atomic_number>23</atomic_number>
      <atomic_mass>50.942</atomic_mass>
      <name>Ванадий</name>
      <electrons_on_layer>2-8-11-2</electrons_on_layer>
      <symbol>V</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>5</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_24">
      <atomic_number>24</atomic_number>
      <atomic_mass>51.996</atomic_mass>
      <name>Хром</name>
      <electrons_on_layer>2-8-13-1</electrons_on_layer>
      <symbol>Cr</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>6</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_25">
      <atomic_number>25</atomic_number>
      <atomic_mass>54.938</atomic_mass>
      <name>Марганец</name>
      <electrons_on_layer>2-8-13-2</electrons_on_layer>
      <symbol>Mn</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>7</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_26">
      <atomic_number>26</atomic_number>
      <atomic_mass>55.845</atomic_mass>
      <name>Железо</name>
      <electrons_on_layer>2-8-14-2</electrons_on_layer>
      <symbol>Fe</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>8</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_27">
      <atomic_number>27</atomic_number>
      <atomic_mass>58.933</atomic_mass>
      <name>Кобальт</name>
      <electrons_on_layer>2-8-15-2</electrons_on_layer>
      <symbol>Co</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>9</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_28">
      <atomic_number>28</atomic_number>
      <atomic_mass>58.693</atomic_mass>
      <name>Никель</name>
      <electrons_on_layer>2-8-16-2</electrons_on_layer>
      <symbol>Ni</symbol>
      <kind>Переходные металлы</kind>
      <position>
        <group>10</group>
        <period>4</period>
      </position>
    </element>
    <element id="e_29">
      <atomic_number>29</atomic_number>
      <atomic_mass>63.546</atomic_mass>
      <name>Медь</name>
